stages:
  - lint
  - test
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUSTUP_HOME: $CI_PROJECT_DIR/.rustup

cache:
  paths:
    - .cargo/
    - target/

lint:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - cargo fmt --check
    - cargo clippy -- -D warnings
  only:
    - merge_requests
    - main

test:
  stage: test
  image: rust:latest
  script:
    - cargo test
  only:
    - merge_requests
    - main

build:
  stage: build
  image: node:18
  before_script:
    - apt-get update && apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - npm install
  script:
    - npm run build
    - npx tauri build --no-bundle
  artifacts:
    paths:
      - src-tauri/target/release/bundle/
    expire_in: 1 week
  only:
    - main
